[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/liyasthomas"
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/liyasthomas"
  force = true

[[redirects]]
  from = "/email"
  to = "mailto:hi@liyasthomas.com"
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/liyasthomas"
  force = true

[[redirects]]
  from = "/calendar"
  to = "https://calendly.com/liyasthomas/30m"
  force = true
