[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/home"
  to = "/"
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/liyasthomas"
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/liyasthomas"
  force = true

[[redirects]]
  from = "/email"
  to = "mailto:hi@liyasthomas.com"
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/liyasthomas"
  force = true

[[redirects]]
  from = "/calendar"
  to = "https://calendly.com/liyasthomas/30m"
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"